name: Run Rijksmuseum API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest pytest-html

      - name: Run tests
        run: |
          pytest test_api.py --html=report.html
          pytest --junitxml=test-results.xml --html=report.html
          continue-on-error: true  # Allows the workflow to continue even if tests fail

      - name: Upload test report
        if: always()  # Ensures artifacts are uploaded even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            report.html 
            test-results.xml
